### ISSUE TITLE
Yakut uavcan.file.GetInfo.0.1 Path.1.0 stringsserialization

### ISSUE THREAD

**Issue by PetervdPerk-NXP** [UAVCAN/yakut#8]
Path1.0 is using the uint8 date type but passing strings to it using Yakut doesn't work.

```
hovergames@hovergames:~/uavcan$ yakut call 42 uavcan.file.GetInfo.0.1 '{path: "/cool/file/here"}'
Traceback (most recent call last):
  File "/home/hovergames/.local/bin/yakut", line 11, in <module>
    sys.exit(main())
  File "/home/hovergames/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/hovergames/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/hovergames/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hovergames/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hovergames/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/hovergames/.local/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/hovergames/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/hovergames/.local/lib/python3.7/site-packages/yakut/cmd/call.py", line 122, in call
    request = pyuavcan.dsdl.update_from_builtin(dtype.Request(), request_fields)
  File "/home/hovergames/.local/lib/python3.7/site-packages/pyuavcan/dsdl/_builtin_form.py", line 150, in update_from_builtin
    update_from_builtin(field_obj, value)
  File "/home/hovergames/.local/lib/python3.7/site-packages/pyuavcan/dsdl/_builtin_form.py", line 126, in update_from_builtin
    f"Invalid format: cannot update an instance of type {type(destination).__name__!r} "
TypeError: Invalid format: cannot update an instance of type 'Path_1_0' from value of type 'str'
hovergames@hovergames:~/uavcan$ 

```

**Comment by pavel-kirienko** [comment]
The correct syntax is `path: {path: "/cool/file/here"}`

or `{path: {path: "/cool/file/here"}}` (outer braces are optional)
